// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_TimeStamp                       26
#define gattdb_modeOfOperation                 29
#define gattdb_isRecording                     31
#define gattdb_Back_TR_PWM_OUT                 33
#define gattdb_Back_TR_PWM_IN                  36
#define gattdb_Front_TR_PWM_OUT                38
#define gattdb_Front_TR_PWM_IN                 41
#define gattdb_Ambient_characteristic_GND         43
#define gattdb_Ambient_characteristic_VDD         46
#define gattdb_Object_characteristic_GND         49
#define gattdb_Object_characteristic_VDD         52

#endif
