// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_Back_TR_PWM_OUT                 26
#define gattdb_Back_TR_PWM_IN                  29
#define gattdb_Front_TR_PWM_OUT                31
#define gattdb_Front_TR_PWM_IN                 34
#define gattdb_Ambient_characteristic_GND         36
#define gattdb_Ambient_characteristic_VDD         39
#define gattdb_Object_characteristic_GND         42
#define gattdb_Object_characteristic_VDD         45

#endif
