// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_front_Desired_Temp_Characteristic         26
#define gattdb_PforPID_Characteristic          28
#define gattdb_IforPID_Characteristic          30
#define gattdb_DforPID_Characteristic          32
#define gattdb_back_Desired_Temp_Characteristic         34
#define gattdb_TimeStamp                       36
#define gattdb_modeOfOperation                 39
#define gattdb_isRecording                     41
#define gattdb_Back_TR_PWM_OUT                 43
#define gattdb_Back_TR_PWM_IN                  46
#define gattdb_Front_TR_PWM_OUT                48
#define gattdb_Front_TR_PWM_IN                 51
#define gattdb_Ambient_characteristic_GND         53
#define gattdb_Ambient_characteristic_VDD         56
#define gattdb_Object_characteristic_GND         59
#define gattdb_Object_characteristic_VDD         62

#endif
